CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS TECH_METRICS (
  TECHNOLOGY VARCHAR,
  GITHUB_REPO VARCHAR,
  GITHUB_STARS NUMBER,
  GITHUB_FORKS NUMBER,
  GITHUB_WATCHERS NUMBER,
  GITHUB_OPEN_ISSUES NUMBER,
  GITHUB_DEFAULT_BRANCH VARCHAR,
  GITHUB_LATEST_RELEASED_AT TIMESTAMP_TZ,
  GITHUB_LAST_COMMIT_AT TIMESTAMP_TZ,
  PYPI_PACKAGE VARCHAR,
  PYPI_DOWNLOADS_LAST_DAY NUMBER,
  PYPI_DOWNLOADS_LAST_WEEK NUMBER,
  PYPI_DOWNLOADS_LAST_MONTH NUMBER,
  INGESTED_AT TIMESTAMP_TZ
);
"""